"""create

Revision ID: db8063a8487e
Revises:
Create Date: 2025-08-23 22:07:56.522403

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "db8063a8487e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("abbreviation", sa.String(), nullable=False),
        sa.Column("fips_code", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_state_abbreviation"), "state", ["abbreviation"], unique=False
    )
    op.create_index(op.f("ix_state_fips_code"), "state", ["fips_code"], unique=False)
    op.create_table(
        "provider",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ccn", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("state_id", sa.Integer(), nullable=True),
        sa.Column("zip_code_five", sa.String(), nullable=False),
        sa.Column("rural_commuting_area", sa.Integer(), nullable=True),
        sa.Column(
            "rural_commuting_area_description",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["state_id"],
            ["state.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_provider_ccn"), "provider", ["ccn"], unique=False)
    op.create_index(op.f("ix_provider_city"), "provider", ["city"], unique=False)
    op.create_index(op.f("ix_provider_name"), "provider", ["name"], unique=False)
    op.create_index(
        op.f("ix_provider_rural_commuting_area"),
        "provider",
        ["rural_commuting_area"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_rural_commuting_area_description"),
        "provider",
        ["rural_commuting_area_description"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_zip_code_five"), "provider", ["zip_code_five"], unique=False
    )
    op.create_table(
        "service",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("discharges", sa.Integer(), nullable=False),
        sa.Column("average_covered_charges", sa.Float(), nullable=False),
        sa.Column("average_total_payments", sa.Float(), nullable=False),
        sa.Column("average_medicare_payments", sa.Float(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["provider.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_average_covered_charges"),
        "service",
        ["average_covered_charges"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_average_medicare_payments"),
        "service",
        ["average_medicare_payments"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_average_total_payments"),
        "service",
        ["average_total_payments"],
        unique=False,
    )
    op.create_index(op.f("ix_service_code"), "service", ["code"], unique=False)
    op.create_index(
        op.f("ix_service_discharges"), "service", ["discharges"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_discharges"), table_name="service")
    op.drop_index(op.f("ix_service_code"), table_name="service")
    op.drop_index(op.f("ix_service_average_total_payments"), table_name="service")
    op.drop_index(op.f("ix_service_average_medicare_payments"), table_name="service")
    op.drop_index(op.f("ix_service_average_covered_charges"), table_name="service")
    op.drop_table("service")
    op.drop_index(op.f("ix_provider_zip_code_five"), table_name="provider")
    op.drop_index(
        op.f("ix_provider_rural_commuting_area_description"), table_name="provider"
    )
    op.drop_index(op.f("ix_provider_rural_commuting_area"), table_name="provider")
    op.drop_index(op.f("ix_provider_name"), table_name="provider")
    op.drop_index(op.f("ix_provider_city"), table_name="provider")
    op.drop_index(op.f("ix_provider_ccn"), table_name="provider")
    op.drop_table("provider")
    op.drop_index(op.f("ix_state_fips_code"), table_name="state")
    op.drop_index(op.f("ix_state_abbreviation"), table_name="state")
    op.drop_table("state")
    # ### end Alembic commands ###
